"""add domain tables

Revision ID: 9a888edcab2e
Revises: 431b25e03cab
Create Date: 2026-05-04 23:34:07.443123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a888edcab2e'
down_revision: Union[str, None] = '431b25e03cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_session_user_uid'), 'chat_session', ['user_uid'], unique=False)
    op.create_table('energy_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_log_logged_at'), 'energy_log', ['logged_at'], unique=False)
    op.create_index(op.f('ix_energy_log_user_uid'), 'energy_log', ['user_uid'], unique=False)
    op.create_table('mood_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_log_logged_at'), 'mood_log', ['logged_at'], unique=False)
    op.create_index(op.f('ix_mood_log_user_uid'), 'mood_log', ['user_uid'], unique=False)
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('kcal_per_serving', sa.Integer(), nullable=False),
    sa.Column('macros', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_user_uid'), 'recipe', ['user_uid'], unique=False)
    op.create_table('water_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ml', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_log_logged_at'), 'water_log', ['logged_at'], unique=False)
    op.create_index(op.f('ix_water_log_user_uid'), 'water_log', ['user_uid'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_session_id'), 'chat_message', ['session_id'], unique=False)
    op.create_table('meal_plan_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('meal', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='meal'), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('food_entry_template', sa.JSON(), nullable=True),
    sa.Column('planned_kcal', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_item_date'), 'meal_plan_item', ['date'], unique=False)
    op.create_index(op.f('ix_meal_plan_item_user_uid'), 'meal_plan_item', ['user_uid'], unique=False)
    op.create_table('shopping_list_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('meal_plan_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_item_id'], ['meal_plan_item.id'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_list_item_user_uid'), 'shopping_list_item', ['user_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_list_item_user_uid'), table_name='shopping_list_item')
    op.drop_table('shopping_list_item')
    op.drop_index(op.f('ix_meal_plan_item_user_uid'), table_name='meal_plan_item')
    op.drop_index(op.f('ix_meal_plan_item_date'), table_name='meal_plan_item')
    op.drop_table('meal_plan_item')
    op.drop_index(op.f('ix_chat_message_session_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_water_log_user_uid'), table_name='water_log')
    op.drop_index(op.f('ix_water_log_logged_at'), table_name='water_log')
    op.drop_table('water_log')
    op.drop_index(op.f('ix_recipe_user_uid'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_mood_log_user_uid'), table_name='mood_log')
    op.drop_index(op.f('ix_mood_log_logged_at'), table_name='mood_log')
    op.drop_table('mood_log')
    op.drop_index(op.f('ix_energy_log_user_uid'), table_name='energy_log')
    op.drop_index(op.f('ix_energy_log_logged_at'), table_name='energy_log')
    op.drop_table('energy_log')
    op.drop_index(op.f('ix_chat_session_user_uid'), table_name='chat_session')
    op.drop_table('chat_session')
    # ### end Alembic commands ###
