"""add api_key table

Revision ID: e17fc69f1b15
Revises: 9a888edcab2e
Create Date: 2026-05-05 00:11:36.405847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e17fc69f1b15'
down_revision: Union[str, None] = '9a888edcab2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uid', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_prefix'), 'api_key', ['prefix'], unique=False)
    op.create_index(op.f('ix_api_key_user_uid'), 'api_key', ['user_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_key_user_uid'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_prefix'), table_name='api_key')
    op.drop_table('api_key')
    # ### end Alembic commands ###
